version: 1.0.{build}
image: Visual Studio 2017
environment:
  _PLATFORM_TOOLSET: v141
artifacts:
  - path: '**\*.exe'
build_script:
  - cmd: msbuild /p:Configuration=Debug /p:Platform=x86 brush/app.xml
  - cmd: msbuild /p:Configuration=Debug /p:Platform=x86 transform/app.xml
