#define HATCH_FOREGROUND_COLOR Gdiplus::Color(255, 0, 0)
#define HATCH_BACKGROUND_COLOR Gdiplus::Color(0, 0, 0)
#define TEXT_FOREGROUND_COLOR Gdiplus::Color(255, 255, 255)
#define TEXT_BACKGROUND_COLOR Gdiplus::Color(80, 80, 80)
#define HATCH_BRUSH_CREATOR(STYLE) [](Gdiplus::Rect& r){ return new Gdiplus::HatchBrush( \
      STYLE, HATCH_FOREGROUND_COLOR, HATCH_BACKGROUND_COLOR); }

SAMPLE samples[] = {
  {
    L"SolidBrush", 
    [](Gdiplus::Rect r){ return new Gdiplus::SolidBrush(HATCH_FOREGROUND_COLOR); },
  },
  {
    L"LinearGradientBrush",
    [](Gdiplus::Rect r){
      return new Gdiplus::LinearGradientBrush(
        Gdiplus::Point(r.X, 0),
        Gdiplus::Point(r.X + r.Width, 0),
        HATCH_FOREGROUND_COLOR,
        HATCH_BACKGROUND_COLOR);
    },
    false,
    true,
  },
  {
    L"PathGradientBrush",
    [](Gdiplus::Rect r){
      Gdiplus::GraphicsPath path(Gdiplus::FillMode::FillModeAlternate);
      path.AddRectangle(r);
      auto b = new Gdiplus::PathGradientBrush(&path);
      b->SetCenterColor(HATCH_FOREGROUND_COLOR);
      Gdiplus::Color colors [] = { HATCH_BACKGROUND_COLOR };
      int colorsL = 1;
      b->SetSurroundColors(colors, &colorsL);
      return b;
    },
    false,
    true,
  },
  // TODO: TextureBrush
  {
    L"HatchBrush\nHatchStyleHorizontal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleHorizontal),
  },
  {
    L"HatchBrush\nHatchStyleVertical",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleVertical),
  },
  {
    L"HatchBrush\nHatchStyleForwardDiagonal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleForwardDiagonal),
  },
  {
    L"HatchBrush\nHatchStyleBackwardDiagonal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleBackwardDiagonal),
  },
  {
    L"HatchBrush\nHatchStyleCross",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleCross),
  },
  {
    L"HatchBrush\nHatchStyleDiagonalCross",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleDiagonalCross),
  },
  {
    L"HatchBrush\nHatchStyle05Percent",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyle05Percent),
  },
  {
    L"HatchBrush\nHatchStyle10Percent",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyle10Percent),
  },
  {
    L"HatchBrush\nHatchStyle20Percent",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyle20Percent),
  },
  {
    L"HatchBrush\nHatchStyle25Percent",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyle25Percent),
  },
  {
    L"HatchBrush\nHatchStyle30Percent",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyle30Percent),
  },
  {
    L"HatchBrush\nHatchStyle40Percent",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyle40Percent),
  },
  {
    L"HatchBrush\nHatchStyle50Percent",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyle50Percent),
  },
  {
    L"HatchBrush\nHatchStyle60Percent",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyle60Percent),
  },
  {
    L"HatchBrush\nHatchStyle70Percent",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyle70Percent),
  },
  {
    L"HatchBrush\nHatchStyle75Percent",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyle75Percent),
  },
  {
    L"HatchBrush\nHatchStyle80Percent",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyle80Percent),
  },
  {
    L"HatchBrush\nHatchStyle90Percent",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyle90Percent),
  },
  {
    L"HatchBrush\nHatchStyleLightDownwardDiagonal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleLightDownwardDiagonal),
  },
  {
    L"HatchBrush\nHatchStyleLightUpwardDiagonal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleLightUpwardDiagonal),
  },
  {
    L"HatchBrush\nHatchStyleDarkDownwardDiagonal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleDarkDownwardDiagonal),
  },
  {
    L"HatchBrush\nHatchStyleDarkUpwardDiagonal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleDarkUpwardDiagonal),
  },
  {
    L"HatchBrush\nHatchStyleWideDownwardDiagonal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleWideDownwardDiagonal),
  },
  {
    L"HatchBrush\nHatchStyleWideUpwardDiagonal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleWideUpwardDiagonal),
  },
  {
    L"HatchBrush\nHatchStyleLightVertical",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleLightVertical),
  },
  {
    L"HatchBrush\nHatchStyleLightHorizontal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleLightHorizontal),
  },
  {
    L"HatchBrush\nHatchStyleNarrowVertical",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleNarrowVertical),
  },
  {
    L"HatchBrush\nHatchStyleNarrowHorizontal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleNarrowHorizontal),
  },
  {
    L"HatchBrush\nHatchStyleDarkVertical",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleDarkVertical),
  },
  {
    L"HatchBrush\nHatchStyleDarkHorizontal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleDarkHorizontal),
  },
  {
    L"HatchBrush\nHatchStyleDashedDownwardDiagonal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleDashedDownwardDiagonal),
  },
  {
    L"HatchBrush\nHatchStyleDashedUpwardDiagonal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleDashedUpwardDiagonal),
  },
  {
    L"HatchBrush\nHatchStyleDashedHorizontal",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleDashedHorizontal),
  },
  {
    L"HatchBrush\nHatchStyleDashedVertical",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleDashedVertical),
  },
  {
    L"HatchBrush\nHatchStyleSmallConfetti",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleSmallConfetti),
  },
  {
    L"HatchBrush\nHatchStyleLargeConfetti",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleLargeConfetti),
  },
  {
    L"HatchBrush\nHatchStyleZigZag",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleZigZag),
  },
  {
    L"HatchBrush\nHatchStyleWave",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleWave),
  },
  {
    L"HatchBrush\nHatchStyleDiagonalBrick",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleDiagonalBrick),
  },
  {
    L"HatchBrush\nHatchStyleHorizontalBrick",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleHorizontalBrick),
  },
  {
    L"HatchBrush\nHatchStyleWeave",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleWeave),
  },
  {
    L"HatchBrush\nHatchStylePlaid",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStylePlaid),
  },
  {
    L"HatchBrush\nHatchStyleDivot",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleDivot),
  },
  {
    L"HatchBrush\nHatchStyleDottedGrid",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleDottedGrid),
  },
  {
    L"HatchBrush\nHatchStyleDottedDiamond",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleDottedDiamond),
  },
  {
    L"HatchBrush\nHatchStyleShingle",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleShingle),
  },
  {
    L"HatchBrush\nHatchStyleTrellis",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleTrellis),
  },
  {
    L"HatchBrush\nHatchStyleSphere",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleSphere),
  },
  {
    L"HatchBrush\nHatchStyleSmallGrid",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleSmallGrid),
  },
  {
    L"HatchBrush\nHatchStyleSmallCheckerBoard",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleSmallCheckerBoard),
  },
  {
    L"HatchBrush\nHatchStyleLargeCheckerBoard",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleLargeCheckerBoard),
  },
  {
    L"HatchBrush\nHatchStyleOutlinedDiamond",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleOutlinedDiamond),
  },
  {
    L"HatchBrush\nHatchStyleSolidDiamond",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleSolidDiamond),
  },
  {
    L"HatchBrush\nHatchStyleTotal\n(Transparent)",
    HATCH_BRUSH_CREATOR(Gdiplus::HatchStyle::HatchStyleTotal),
    true,
  },
  {
    NULL,
  } // End of array
};
